# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34293c6390bdb52bfe8415f354497e288021469dfa5b7233ae606a10afb068737bb47ab7d60d8bfdc435bbcebd250f4ccb5a77d7a292314d0c8ccd0ff22fea58

test:
  secret_key_base: d8f5adbd29c1c3ec0eb5b46548b8e435501c0f071ab275a5ad689cf98d485d52776d56f11eb5a43adf1dfd8e3a97bdf5037e102d57ffb422353a3cdaead5bbb6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
